version: "2"

services:
  app:
    build: .
    ports:
      - "80:8080"
    volumes:
      - .:/var/www/html
    links:
      - db
      - adminer

  db:
    image: postgres:12.1
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: sandbox
      POSTGRES_USER: root
      POSTGRES_PASSWORD: secret

  adminer:
    image: adminer:4.7.5
    ports:
      - "8080:8080"